sudo: required
services:
- docker
branches:
  only:
  - master
script:
- docker build -t $REPO:$COMMIT .
after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- curl -X POST https://hooks.microbadger.com/images/transactcharlie/docker-nuitka/Fi3fCnOKaacCGY2IeR1pRKkImqg=
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=transactcharlie/docker-nuitka
  - secure: KQOBsNqI25VTdrG39Ip91bbbA/0BbnSteq0jdFiimva0WcXu+dXn/qzdTbG0jxLx0xa6Pa3nAAffAIa2SI0QBHhVqvBdJxlJfIDrJD3gxTZBkYx4XRZPp9B1eFiohXoSmiuMKQBizF+3H0oA5nMV9AFPDpfAr/6uRrPh3VbG3jkM8UwbENZBnu6/fcBpSMnsyVmK3CtqYvATPnMagmHq5Mu+jsf2qFMcFoRgOhvFdNmkCjev1+8+U/A0ZT+hbmxf/OF3+Wg/ZbEKZiXTkdjsVl7yTLdU54ZXPteMpH2JV3VyDI4y1owVuYguupxWYi0DduTJ+c589EQ2wMJI4M59wmsFZwhzUapD9xMKaCm+DUOdZHl217klfNML3eGZOmI96ootG9O+8oi4R9wIJHyvqYCZ5PCX34JtluzQPjSch9/ZRh73YGpro+yORrKNypLnbPDZu1qNAKuRvRo+5vGZca1Jz4+GK0mzRofBY5Z9PUR6HqfUWjzp6XY/Nfy/Wg30MfRf4BOueFGnD3YyozHDWAwPeuZbBCQ9PYVihukgbgn0LLXeDOd5pueqrtOMR2fln8CP6JUlohu1Ro843kzc/8mW7T0UP/IPVsxTMfpV6/9IcNgvWppp2yNZO1BAH/fxh+XS0lME9V0X5aNIASX6dxcIk60+nBCLrdQQP2xMoWs=
  - secure: CVEekEBs83oFIm9+PvT7S8vQIIJH0V+iXNgKY7IbpPnxSAyg//wsAVGa5rsdq31V5LCBm/sq2MBCnpAT47w4/n0QDK/MDt1gCDH6/P8u5dUb9U4Z4rhcrnl8jWAyprRvHX7QaiPQGpnqnteiqVKJAoVq34I+rkupUgrej763gZoStMCGXUeKAcOjPtyFsHnsuLBMG2uE179FXfZLiRiwXnXyFJfClFuACPZqCl7nLfskobAIdwdch9GEXC8Ca6LxEUp3VzYYRz+SNknQAQ5GwvFbPeK3aV+pFVbzDLL+tY9aCg9+VsSmIZM0TboJTp88dB3adr5LrFppnh8r5ZQFw3R0uRd8j+1Q6KIfc/Adiph3Ns07KpAQUBM0MKNJJlmQUSKoIfiAdXX0FsLRpXreKK+I2cMwAHsdZZbKl/WWWIXwg9RcumAQctOEGVlNqVCLbgUSX2RqQbeOCL7xFAKTKfTH6rV/ZDM+PbQ3f+mF96j7Zs5fBvYG1dLL8mEzyNBUEdJJznHlAqqH/SpVo+CwMdjzbVLpeX3gS6ifboLQc+o08YtDF1NFMI95KWXtmoIqBhEYH4C4iIVo5N+nSQah9dQRF2CHspOl08nLXFyJj+6MdqBhs+jfO1nPFh9aqSYTSZ4D3AjOIJymKKpy1OuHzaM5xVOd3WIZmZgVM0LVO0A=
